---
# tasks file for administrasi-cisco
- name: create production vlan
  ios_vlans:
    config:
      - name: tiga
        vlan_id: 3
        state: active
        shutdown: disabled
      - name: twenty
        vlan_id: 20
        mtu: 610
        state: active
        shutdown: enabled
- name: update interface         
  ios_interface:
    config:
      - name: GigabitEthernet0/0
        description: 'uplink'
      - name: GigabitEthernet0/1
        description: 'perminyakan'
