---
# tasks file for administrasi-cisco
- name: create production vlan
  ios_vlans:
    config:
      - name: tiga
        vlan_id: 3
        state: active
        shutdown: disabled
      - name: twenty
        vlan_id: 20
        mtu: 610
        state: active
        shutdown: enabled
- name: Override device configuration of all l2 interfaces with provided configuration
  ios_l2_interfaces:
    config:
      - name: GigabitEthernet0/3
        access:
          vlan: 30
    state: overridden
- name: remove and Add vlan interface using ios_interfaces
  ios_interfaces:
    config:
      - name: vlan23
        description: "VLAN23_test"
        enabled: False
      - name: vlan32
        description: "VLAN32_ipaddress"
        enabled: True
      - name: vlan12
        description: "plantation"
        enabled: True 
    state: merged
- name: configure interface settings
  ios_config:
    lines:
      - description test interface
      - ip address 172.31.1.1 255.255.255.0
    parents: interface vlan12
