---
# tasks file for administrasi-cisco
- name: create production vlan
  ios_vlans:
    config:
      - name: tiga
        vlan_id: 3
        state: active
        shutdown: disabled
      - name: twenty
        vlan_id: 20
        mtu: 610
        state: active
        shutdown: enabled
- name: Override device configuration of all l2 interfaces with provided configuration
  ios_l2_interfaces:
    config:
      - name: GigabitEthernet0/3
        access:
          vlan: 30
    state: overridden
- name: remove and Add vlan interface using ios_interfaces
  ios_interfaces:
    config:
      - name: vlan23
        description: "VLAN23_test"
        enabled: False
      - name: vlan32
        description: "VLAN32_ipaddress"
        enabled: True
      - name: vlan12
        description: "plantation"
        enabled: True 
    state: merged
- name: add ip address for vlan interface using ios_L3_interfaces
  ios_l3_interfaces:
    config:
      - name: vlan32
        ipv4:
        - address: 192.168.1.23/32
      - name: GigabitEthernet1/3
        ipv4:
        - address: 192.168.168.1/24
      - name: GigabitEthernet1/2
        ipv4:
        - address: 192.168.16.16 255.255.255.0
      - name: vlan12
        ipv4:
        - address: 192.168.24.24 255.255.255.0
          secondary: True
    state: replaced

