---
# tasks file for administrasi-cisco
- name: create production vlan
  ios_vlans:
    config:
      - name: tiga
        vlan_id: 3
        state: active
        shutdown: disabled
      - name: twenty
        vlan_id: 20
        mtu: 610
        state: active
        shutdown: enabled
- name: Override device configuration of all l2 interfaces with provided configuration
  ios_l2_interfaces:
    config:
      - name: GigabitEthernet0/3
        access:
          vlan: 30
    state: overridden
- name: Add interface using aggregate
  ios_interface:
    aggregate:
    - { name: loopback1, description: test-interface-1 }
    - { name: loopback2, description: test-interface-2 }
    duplex: full
    state: present
