---
# tasks file for satu
- name: create loopback0
  ios_interfaces:
    config:
      - name: loopback 0
        enabled: True
- name: setup IP Address
  ios_l3_interfaces:
    config:
      - name: loopback0
        ipv4:
        - address: 1.1.1.1/32
      - name: GigabitEthernet0/0
        ipv4:
        - address: 12.12.12.1 255.255.255.0
    state: merged
- name: setup ospf
  ios_config:
    lines:
      - router-id 1.1.1.1
      - network 1.1.1.1 0.0.0.0 area 0
      - network 12.12.12.1 0.0.0.0 area 1
    parents:
      - router ospf 1
