---
# tasks file for enam
- name: create loopback0
  ios_interfaces:
    config:
      - name: loopback0
        enabled: True
- name: add IP Address Router enam
  ios_l3_interfaces:
    config:
      - name: loopback0
        ipv4:
        - address: 2.2.2.2/32
      - name: GigabitEthernet0/0
        ipv4:
        - address: 12.12.12.2/24
      - name: GigabitEthernet0/1
        ipv4:
        - address: 23.23.23.2/24
    state: merged
- name: add ospf 
  ios_config:
    lines:
      - router-id 2.2.2.2
      - network 2.2.2.2 0.0.0.0 area 1
      - network 12.12.12.2 0.0.0.0 area 1
      - network 23.23.23.2 0.0.0.0 area2
    parents:
      - router ospf 2
- name: enable interface gi 0/0-1
  ios_config:  
    lines:
      - no shutdown
    parents:
      - int ra Gi 0/0-1
- name: update hostname
  ios_config:
    lines: hostname {{ inventory_hostname }}
